force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>Custom objects hold the name of the category with which the product will be associated.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <description>Custom salesforce object which will be the child of category and product to link product and category.</description>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>The category for the product</inlineHelpText>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>Product_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The product for the category</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Images__c/Product_Images__c.object-meta.xml
<CustomObject>
    <description>A Child object to the Product that will store the Images related to the Product</description>
    <label>Product Images</label>
    <nameField>
        <label>Product Images Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Imageses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Images__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The related product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Imageses</relationshipLabel>
    <relationshipName>Product_Imageses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductDetailsController.cls
public with sharing class ProductDetailsController {
    @AuraEnabled(cacheable=true)
    Public static List<Product2> getProductDetails(string productId){
      Return [SELECT id, Name, RemainingQuantity__c, Description, Stock_Status__c,(SELECT URL__c FROM Product_Imageses__r ),(SELECT UnitPrice FROM PricebookEntries) 
       FROM Product2 WHERE id =:productId];
       //Return [SELECT id, Name, RemainingQuantity__c FROM Product2 WHERE id in (SELECT Product__c FROM Product_Category__c WHERE Category__c =:categIds)];
    
    }
}