force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>Custom objects hold the name of the category with which the product will be associated.</description>
    <label>Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/ParentCategory__c.field-meta.xml
<CustomField>
    <fullName>ParentCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The parent category if this is the child category</inlineHelpText>
    <label>Parent Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/Product_Category__c.object-meta.xml
<CustomObject>
    <description>Custom salesforce object which will be the child of category and product to link product and category.</description>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>The category for the product</inlineHelpText>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>Product_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The product for the category</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Categories</relationshipLabel>
    <relationshipName>Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Images__c/Product_Images__c.object-meta.xml
<CustomObject>
    <description>A Child object to the Product that will store the Images related to the Product</description>
    <label>Product Images</label>
    <nameField>
        <label>Product Images Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Imageses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Images__c/fields/Hero_Image__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If Selected this image will be displayed on the Product List Page</inlineHelpText>
    <label>Hero Image</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Images__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The related product</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Imageses</relationshipLabel>
    <relationshipName>Product_Imageses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductCategoriesController.cls
Public without sharing class ProductCategoriesController {
    //query all categories from category object send it to parent js
    @AuraEnabled(cacheable=true)
    Public static List<Category__c> getAllCategories(){
        Return [SELECT id, Name, ParentCategory__c FROM Category__c];
    }
    //get category ids from js and queried all products wtih needed information and to main js
    @AuraEnabled(cacheable=true)
    Public static List<Product2> getAllProduct(List<string> categIds){
      Return [SELECT id, Name, RemainingQuantity__c, (SELECT URL__c, Hero_Image__c FROM Product_Imageses__r ),(SELECT UnitPrice FROM PricebookEntries) 
       FROM Product2 WHERE id IN (SELECT Product__c FROM Product_Category__c WHERE Category__c in:categIds)];
     }
}